print("Hello,type your name.")
n=str(input())
print("Hello",n,"How are you ?")
print("which place are you in?")
n=str(input())
p=str(input())
print("Hello",n,"How is Weather in",p)
print("what is your age")
age=int(input())
print("my age is",age)
