n=str(input("enter your name ->"))
p=str(input("type your location->"))
print("Hello",n,"How is the weather in",p,"?")
age=int(input("What is your age?->"))
print("Good to know that you are",age,"years old.")